# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    puts options[:DEV_FIREBASE_APP_ID]
    firebase_app_distribution(
      app: options[:DEV_FIREBASE_APP_ID],
      firebase_cli_token: options[:DEV_FIREBASE_CLI_TOKEN],
      apk_path: "../build/app/outputs/flutter-apk/app-profile.apk",
      groups: "Developers",
      release_notes: options[:RELEASE_NOTES]
    )
  end
end
