name: Comments

on: 
  pull_request_review_comment:
    type: [edited]
    branches: [ main ]

jobs:
  installation:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: echo
      - run: echo "rodou app"
